spring:
  data:
    mongodb:
      uri: mongodb+srv://user:pass@galeras.vjcyxol.mongodb.net/cashflow
ledger:
  base-url: http://localhost:8080/

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE

server:
  port: 8080